/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Getting Started
  gettingStartedSidebar: [
    {
      type: "autogenerated",
      dirName: "getting-started",
    },
  ],
  // Cyber Security
  networkSecuritySidebar: [
    {
      type: "autogenerated",
      dirName: "cs/ns",
    },
  ],
  applicationSecuritySidebar: [
    {
      type: "autogenerated",
      dirName: "cs/as",
    },
  ],
  informationSecuritySidebar: [
    {
      type: "autogenerated",
      dirName: "cs/is",
    },
  ],
  incidentResponseSidebar: [
    {
      type: "autogenerated",
      dirName: "cs/ir",
    },
  ],
  // Cloud Security
  awsSidebar: [
    {
      type: "autogenerated",
      dirName: "cloudsec/aws",
    },
  ],
  azureSidebar: [
    {
      type: "autogenerated",
      dirName: "cloudsec/azure",
    },
  ],
  cloudInfrastructureSecuritySidebar: [
    {
      type: "autogenerated",
      dirName: "cloudsec/cis",
    },
  ],
  identityAccessManagementCloudSidebar: [
    {
      type: "autogenerated",
      dirName: "cloudsec/iamc",
    },
  ],
  compliancePrivacyCloudSidebar: [
    {
      type: "autogenerated",
      dirName: "cloudsec/cpc",
    },
  ],
  // DevSecOps
  sastSidebar: [
    {
      type: "autogenerated",
      dirName: "devsecops/sast",
    },
  ],
  scaSidebar: [
    {
      type: "autogenerated",
      dirName: "devsecops/sca",
    },
  ],
  gitopsSidebar: [
    {
      type: "autogenerated",
      dirName: "devsecops/gitops",
    },
  ],
  dastSidebar: [
    {
      type: "autogenerated",
      dirName: "devsecops/dast",
    },
  ],

  // Infrastructure Automation
  ansibleSidebar: [
    {
      type: "autogenerated",
      dirName: "infraauto/ansible",
    },
  ],
  chaosengSidebar: [
    {
      type: "autogenerated",
      dirName: "infraauto/chaoseng",
    },
  ],
  k8sSidebar: [
    {
      type: "autogenerated",
      dirName: "infraauto/k8s",
    },
  ],
  terraformSidebar: [
    {
      type: "autogenerated",
      dirName: "infraauto/terraform",
    },
  ],
  pulumiSidebar: [
    {
      type: "autogenerated",
      dirName: "infraauto/pulumi",
    },
  ],
  infrastructureMonitoringAlertingSidebar: [
    {
      type: "autogenerated",
      dirName: "infraauto/ima",
    },
  ],
  // Quick References
  quickRefsSidebar: [
    {
      type: "autogenerated",
      dirName: "quickrefs",
    },
  ],
};


module.exports = sidebars;
